"""
Configuration module for RIM application.
"""

from config.settings import (
    APP_CONFIG,
    TPO_CLUSTERS,
    RISK_CATEGORIES,
    RISK_LEVELS,
    RISK_STATUSES,
    RISK_ORIGINS,
    MITIGATION_TYPES,
    MITIGATION_STATUSES,
    MITIGATION_EFFECTIVENESS,
    INFLUENCE_STRENGTHS,
    IMPACT_LEVELS,
    NEO4J_DEFAULTS,
    GRAPH_DEFAULTS,
    ANALYSIS_CACHE_TIMEOUT,
)

# Convenience exports for app.py
APP_TITLE = APP_CONFIG["page_title"]
APP_ICON = APP_CONFIG["page_icon"]
LAYOUT_MODE = APP_CONFIG["layout"]
NEO4J_DEFAULT_URI = NEO4J_DEFAULTS["uri"]
NEO4J_DEFAULT_USER = NEO4J_DEFAULTS["username"]

__all__ = [
    "APP_CONFIG",
    "APP_TITLE",
    "APP_ICON",
    "LAYOUT_MODE",
    "TPO_CLUSTERS",
    "RISK_CATEGORIES",
    "RISK_LEVELS",
    "RISK_STATUSES",
    "RISK_ORIGINS",
    "MITIGATION_TYPES",
    "MITIGATION_STATUSES",
    "MITIGATION_EFFECTIVENESS",
    "INFLUENCE_STRENGTHS",
    "IMPACT_LEVELS",
    "NEO4J_DEFAULTS",
    "NEO4J_DEFAULT_URI",
    "NEO4J_DEFAULT_USER",
    "GRAPH_DEFAULTS",
    "ANALYSIS_CACHE_TIMEOUT",
]
