name: Deploy to Cloud Run

on:
  push:
    branches: [ main ] # Se déclenche quand vous poussez sur la branche 'main'

env:
  PROJECT_ID: rim-app-test
  REGION: europe-west3
  SERVICE_NAME: rim-app

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Docker Auth
      run: gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet

    - name: Configure Docker
      run: gcloud auth configure-docker europe-west3-docker.pkg.dev

    - name: Build and Push Image
      run: IMAGE_URL="europe-west3-docker.pkg.dev/${{ env.PROJECT_ID }}/rim-repo/${{ env.SERVICE_NAME }}:${{ github.sha }}"
        docker build -t $IMAGE_URL .
        docker push $IMAGE_URL

    - name: Deploy to Cloud Run
      run: |-
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image europe-west3-docker.pkg.dev/${{ env.PROJECT_ID }}/rim-repo/${{ env.SERVICE_NAME }}:${{ github.sha }} \
          --region ${{ env.REGION }} \
          --platform managed \
          --allow-unauthenticated \
          --set-secrets="NEO4J_URI=NEO4J_URI:latest,NEO4J_USER=NEO4J_USER:latest,NEO4J_PASSWORD=NEO4J_PASSWORD:latest"